<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Contact Form</title>';
echo '<link rel="stylesheet" href="StyleWeCare_HubungiKami.css">';
echo '</head>';
echo '';
echo '<body>';
echo '<div class="container">';
echo '';
echo '<div class="card-container">';
echo '<div class="left">';
echo '<div class="left-container">';
echo '<h2>Hubungi Kami</h2>';
echo '<p>WeCare melayani perawatan hewan peliharaan. Kami akan membantu hewan peliharaan anda untuk mendapatkan perhatian, perawatan dan kasih sayang yang mereka butuhkan sepanjang perawatan.</p>';
echo '<br>';
echo '<p>Because Loving is Caring💜</p>';
echo '</div>';
echo '</div>';
echo '<div class="right">';
echo '<div class="right-container">';
echo '<form action="">';
echo '<h2 class="sm-view">Hubungi Kami</h2>';
echo '<input type="text" placeholder="Nama">';
echo '<input type="email" placeholder="Alamat Email">';
echo '<input type="text" placeholder="Perusahaan" autocomplete="off">';
echo '<input type="phone" placeholder="Telepone" autocomplete="off">';
echo '<textarea rows="10" placeholder="Pesan"></textarea>';
echo '<button>Kirim</button>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</body>';
echo '';
echo '</html>';
?>